<div class="title">
	<p>B&amp;W Film, no sound, 10&rsquo; 39&rsquo;&rsquo; 2012,<br />Film extract, Film part of the Installation <a href="/work/vanishing_point">Vanishing Point</a></p>
</div>			
<div class="text">
	<p class="english">The video analysed the representation of Chinese landscape trough the parallel perspective and the overlapping of different layers of mountains in order to achieve the sense of deepness. The different lays are overlapped through slow and almost not perceivable fades in and fades out of the same mountains landscape, The image appears still but is moving where the mountains crests oscillate like sea waves </p>
	<p class="english">The 16mm black and white film is made with a selection of photographs and words shot with rostrum camera. The film is hand processed. The selection comprises excerpts from films and books1 pointing out the connection of the mountain with the origin of the world. Especially in relation to the notion of mountain as a of holy place, closest to the heaven, were immortals reside. This is compared with the challenging of conquering mountains as for western culture in terms of climbing the highest mountains thus Mount Everest. It is physically impossible to survive above 26,000 ft, that is what is called death zone on Everest were corpse of died climbers will ever been. Moreover the physical effect of hight altitude on human being leads to death, even, in some cases, where external oxygen supply is provided. The film is though in order to construct a new story between myth, popular legend and true mountaineering experience through and editing of texts excerpts and mountain&rsquo;s images.</p>
	<p class="english">1Film: Fata Morgana (Mirage) 1971 Werner Herzog, Ten Minutes older, the Cello, 2002 Michelangelo Bertolucci.<br />Books: The Everest:summit of achievement Stephen Venables, First ascent Stephen Venables, Book of modern mountaineering Malcolm Milne, Top climbs of the world<br />Garth Hatting, Mount blanc and the Aiguilles, C.Douglas Milner.</p>
	<p class="italian">Il film &egrave; realizzato attraverso una selezione di testi ed immagini girato con il Rostrum Camera, sviluppato e stampato a mano. La selezione comprende estratti presi da testi e sceneggiature dove la montagna &egrave; vista come luogo sacro collegata alle origini del mondo, specialmente in relazione alla sua rappresentazione sacra di posto da contemplare, pi&ugrave; vicino al paradiso dive risiedono gli immortali. Questa concezione &egrave; paragonata all&rsquo; idea occidentale di vetta da conquistare e a testimonianze di scalatori alla prese della conquista del Monte Everest dove ad un altezza superiore ai 26.000 piedi &egrave; fisicamente impossibile sopravvivere. Questa zona &egrave; chiamata &ldquo;La zona morta&rdquo;. Gli effetti psicofisici dell&rsquo;altitudine sull&rsquo;essere umano portano in alcuni casi alla morte anche se sono usate risorse esterne di ossigeno. Molti sono gli scalatori morti durante i tentativi di conquista della vetta e i loro cadaveri sono e rimarranno nella zona morta per sempre perch&egrave; molto difficile e pericoloso scendere questi corpi a valle. Questo film &egrave; pensato in modo da ricostruire un nuova storia tra mito, legenda popolare e vere testimonianze attraverso la rielaborazione e l&rsquo;associazione di estratti di di testi ed i immagini<br />1Film: Fata Morgana (Mirage) 1971 Werner Herzog, Ten Minutes older, the Cello, 2002 Michelangelo Bertolucci.</p>
	<p class="italian">Books: The Everest:summit of achievement Stephen Venables, First ascent Stephen Venables, Book of modern mountaineering Malcolm Milne, Top climbs of the world<br />Garth Hatting, Mount blanc and the Aiguilles, C.Douglas Milner</p>
</div>