<div class="text english">
	<p>The project comprises of a three channel video and a 16mm b&amp;w film. The focus of this piece is the study of landscape in Chinese Shan Shui painting and the holy aspect of mountain for eastern culture in relation to our representation codes. In western linear perspective we know the vanishing point is related to a specific point where all lines terminate, as the deepness point in our vision field.</p>
	<p>In parallel perspective and in old Chinese landscape depiction, there is no linear perspective, but horizontal and parallel layers that overlap each other in a sort of endless field extension which creates deepness, thus parallel perspective. My trip across the mountains along the north west of Beijing made me understand how these representation codes were conceived in old Chinese landscape painting. The videos show long static shots of mountain landscapes which overlap each other through slow and delicate fades in and fades out made in postproduction in order to amplify the sense of endless deepness of field. The fades are extremely soft and the images imperceptibly change, thus the mountains depicted seems still but they are in movement. This creates a sort of ambiguity between what was actually the shooting and what is made in post-production through the juxtaposition of different shots.</p>
	<p>The 16mm black and white film is made with a selection of photographs and words shot with rostrum camera. The film is hand processed. The selection comprises exerts from films and books pointing out the connection of the mountain with the origin of the world. Especially in relation to the notion of the mountain as a holy place, closest to the heaven, were immortals reside. This is compared with the challenging of conquering mountains as for western culture in terms of climbing the highest mountains thus Mount Everest. It is physically impossible to survive above 26,000 ft, that is what is called death zone on Everest were corpses of died climbers will forever be. Moreover the physical effect of hight altitude on a human being leads to death, even, in some cases, where external oxygen supply is provided. The film is though in order to construct a new story between myth, popular legend and true mountaineering experience through and editing of texts excerpts and mountain&rsquo;s images.</p>
	<p>1Film: Fata Morgana (Mirage) 1971 Werner Herzog, Ten Minutes older, the Cello, 2002 Michelangelo Bertolucci.</br>Books: The Everest:summit of achievement Stephen Venables, First ascent Stephen Venables, Book of modern mountaineering Malcolm Milne, Top climbs of the world Garth Hatting, Mount blanc and the Aiguilles, C.Douglas Milner</p>
</div>

<div class="text italian">
	<p>Il lavoro verte sullo studio della rappresentazione del paesaggio nella pittura Shan Shui cinese e la sacralit&agrave; della montagna nelle culture orientali in relazione alla concezione occidentale come vetta da conquistare. Nella prospettiva lineare il punto di fuga rappresenta il punto di profondit&agrave; specifico dove tutte le linee convergono. Mentre nella prospettiva parallela ci sono diversi piani orizzontali che si sovrappongono fino all&rsquo;infinito ricreando il senso di profondit&agrave;. Il mio viaggio attraverso le montagne a nord-est di Pechino mi ha fatto capire come i codici di rappresentazione secondo la prospettiva parallela e nella rappresentazione del paesaggio nella pittura cinese siamo stati concepiti. Il video mostra inquadrature fisse di paesaggi montani sovrapposti attraverso lente e delicate dissolvenze che restituiscono un&rsquo;immagine apparentemente fissa ma in realt&agrave; in movimento, dove il senso di profondit&agrave; &egrave; accentuato secondo la sovrapposizione di ulteriori piani orizzontali di paesaggio. Questo crea una sorta di ambiguit&agrave; tra quello che &egrave; stato girato e quello rielaborato in post post produzione attraverso la sovrapposizione di diversi shots.</p>
	<p>Il film &egrave; realizzato attraverso una selezione di testi ed immagini girato con il Rostrum Camera, sviluppato e stampato a mano. La selezione comprende estratti presi da testi e sceneggiature dove la montagna &egrave; vista come luogo sacro collegata alle origini del mondo, specialmente in relazione alla sua rappresentazione sacra di posto da contemplare, pi&ugrave; vicino al paradiso dive risiedono gli immortali. Questa concezione &egrave; paragonata all&rsquo; idea occidentale di vetta da conquistare e a testimonianze di scalatori alla prese della conquista del Monte Everest dove ad un altezza superiore ai 26.000 piedi &egrave; fisicamente impossibile sopravvivere. Questa zona &egrave; chiamata &ldquo;La zona morta&rdquo;. Gli effetti psicofisici dell&rsquo;altitudine sull&rsquo;essere umano portano in alcuni casi alla morte anche se sono usate risorse esterne di ossigeno. Molti sono gli scalatori morti durante i tentativi di conquista della vetta e i loro cadaveri sono e rimarranno nella zona morta per sempre perch&egrave; molto difficile e pericoloso scendere questi corpi a valle. Questo film &egrave; pensato in modo da ricostruire un nuova storia tra mito, legenda popolare e vere testimonianze attraverso la rielaborazione e l&rsquo;associazione di estratti di di testi ed i immagini</p>
</div>